### PR TITLE
game achievements

### PR DESCRIPTION
**Pull request by zamitto**

### CODE REVIEW

**Comment by Shisuiicaro** [comment]
Hey, i am testing this feature, and just to let you know i found a game that uses 

> steamdata>user_stats.ini
And the files look's like that
```
[ACHIEVEMENTS]
"ach_firstday" = {unlocked = true, time = 1728057507}
"ach_welcome" = {unlocked = true, time = 1728056150}
```

Would be cool if you add that type of file for achievements too (currently this file doesn't work with the launcher achievements feature)

**Comment by zamitto** [comment]
> Hey, i am testing this feature, and just to let you know i found a game that uses `steamdata>user_stats.ini` And the files look's like that:
> 
> ```
> [ACHIEVEMENTS]
> "ach_firstday" = {unlocked = true, time = 1728057507}
> "ach_welcome" = {unlocked = true, time = 1728056150}
> ```
> 
> Would be cool if you add that type of file for achievements too (currently this file doesn't work with the launcher achievements feature)

Where the `steamdata` folder located?
It is inside the game folder? Or somewhere else in your computer?
If you could provide the whole file path would be great

**Comment by Shisuiicaro** [comment]
> Where the `steamdata` folder located? It is inside the game folder? Or somewhere else in your computer? If you could provide the whole file path would be great

Sure, `D:\Games\The Operator\SteamData\user_stats.ini`

**Review by Gabuabuu — APPROVED** [review]

**Review by Gabuabuu — APPROVED** [review]

**Review by thegrannychaseroperation — APPROVED** [review]
LGTM

**Pull request merged**
