### PR TITLE
feat: add thebyrut repack parser

### PR DESCRIPTION
**Pull request by luvvvdev**
add byruthub.org source parser

### CODE REVIEW

**Comment by chubbygrannychaser** [comment]
Please fix lint

**Comment by chubbygrannychaser** [comment]
Plus, I cannot see this repack being mentioned on any megathread. Could you link it?

**Comment by xxDRV** [comment]
> byruthub.org



> Plus, I cannot see this repack being mentioned on any megathread. Could you link it?

Link is fine but this is not a repacker, this is a tracker which is not an official source of any release group.

**Comment by chubbygrannychaser** [comment]
@xxDRV is it safe though? Where can I find any reference for this?

**Comment by chubbygrannychaser** [comment]
Closing this since I couldn't find any reference for this tracker on any megathread.

**Pull request closed without merging**
