### PR TITLE
build(linux): add flatpak/rpm package and remove snap

### PR DESCRIPTION
**Pull request by fhilipecrash**
- Remove snap package from build because flatpak and appimage are more used
- Add mimeType to handle `hydralauncher://` protocol

### CODE REVIEW

**Comment by zamitto** [comment]
I think you would also need to update the build.yml file

image

**Comment by zamitto** [comment]
Closing as done in #487
I took your branch, rebased and added the commented change

**Comment by zamitto** [comment]
I actually removed the flatpak from my PR as the build was failing, so it is still open to do

**Comment by iMonZ** [comment]
> I actually removed the flatpak from my PR as the build was failing, so it is still open to do

Hey could you then reopen this PR? That would be nice

**Pull request closed without merging**
