### PR TITLE
docs: Updated header titles for consistency

### PR DESCRIPTION
**Pull request by codesmith-emmy**

### CODE REVIEW

**Review by piradata — COMMENTED** [review]
could you also add <a> tags on the headers you changed to be the same as the ones un the table of contents? that way when on creates a new readme based on the english one they dont have to worry about forgetting to change the linking name on the TOC (table of contents) to the headers

**Comment by codesmith-emmy** [comment]
I have now added tags on the header titles to update the table of contents automatically

**Comment by piradata** [comment]
LGTM

**Comment by zamitto** [comment]
The lint verification is failing, could you test to see why?

**Comment by thegrannychaseroperation** [comment]
No need to capitalize every single word.

**Pull request closed without merging**
