### PR TITLE
Fixed incorrect translation of variable in italian translation

### PR DESCRIPTION
**Pull request by Giasko0**
Fixed variable that should not be translated

### CODE REVIEW

**Comment by zamitto** [comment]
Would you like to also translate some missing strings in Italian?

image

**Comment by Giasko0** [comment]
Sure. I will add the missing strings as soon as I can

**Comment by Giasko0** [comment]
I added the missing translations, but i could not find game_details.settings and settings.real_debrid_api_token_description as they were not in the english locale file

**Review by zamitto — APPROVED** [review]
LGTM, thanks

About the variables you mentioned, I think that they are not being used anymore.

**Pull request merged**
