### PR TITLE
Feature change language & Fullscreen options in settings

### PR DESCRIPTION
**Pull request by darkjontex**
Including options in settings to allow:

- Open Hydra Launcher in Fullscreen mode or custom resolution.
- Change the Language system for a custom one.

Everything is saved as userPreferences, so if you clear your Hydra Launcher Cache, everything is reset.

I hope you guys can implement or use part of the code.
Once again, thanks for the project Hydra Launcher.

### CODE REVIEW

**Comment by darkjontex** [comment]
Someone from Los Broxas quem review my PR? I would like to contribute with those features for Hydra Launcher.

**Comment by darkjontex** [comment]
- Fixed points about Style and Select component for Language.
- Removed Input Fields for Resolution.

image

image

**Comment by zamitto** [comment]
Ok, i took a better look into your PR. There are some problems:
1. A lot of comments
2. Your PR aims to do 2 things (persist screen resolution and change language)
3. None of these things seems done
4. Your options inside the Select are hard coded. If you want to work on this feature, you need to figure out a way to dinamically load your options so we dont have to revisit this component every time a new localization is added

I will have to close this PR, and I suggest you do only one thing per PR.

**Comment by piradata** [comment]
does not seems so hard to make it dynamic, its vasically do the sabe thaat the localization plugin does, reading the folders at the localization directory. u can use the same var it uses and convert the local code back to language name

**Comment by piradata** [comment]
does not seems so hard to make it dynamic, its vasically do the sabe thaat the localization plugin does, reading the folders at the localization directory. u can use the same var it uses and convert the local code back to language name

**Comment by piradata** [comment]
will take a look at the language changer later this week if no one does, seems funny

**Comment by darkjontex** [comment]
ok

**Pull request closed without merging**
