### PR TITLE
Add French README

### PR DESCRIPTION
**Pull request by alexandregv**
I chose to let some english words because they make more sense like that.

### CODE REVIEW

**Comment by rhayonne** [comment]
Salut @alexandregv , je suis brésilien habitant en France.
Je voudrais justement faire une traduction du projet Hydra

Hi @alexandregv , i'm brazilian, living in Normandy - France
I thinked the same, i want help to translate Hydra to French.
What's happenend, you know more about merge politics?

**Comment by Lianela** [comment]
Looks like verifications failed and is outdated your version, try to check that and if it everything is correct, probably will be merged

**Comment by alexandregv** [comment]
The CI failed due to a network error querying the arch linux repos. It is not caused by my modifications, and may work if the CI is re-launched.

**Comment by zamitto** [comment]
I'm gonna merge this. But soon we are going to update the main README, as the project does not use python anymore, and some other relevant changes

**Review by zamitto — APPROVED** [review]

**Pull request merged**
