### PR TITLE
[Locales] Added Hungarian language support

### PR DESCRIPTION
**Pull request by ferivoq**
Hey! I stumbled upon this project on Reddit and I really like the conception!!!
I added Hungarian language hope you like it :D
Szívesen

### CODE REVIEW

**Comment by hydralauncher** [comment]
Awesome. Please consider joining our Discord server, since we constantly add new strings to Hydra, it would be good to have someone with Hungarian knowledge in order to review translations.

**Comment by readyornoot** [comment]
FGBJFGJG

**Comment by ferivoq** [comment]
Hey! I joined the server, a little bit of recommendation, u should add a text channel for translators where the main language is english! Thanks for merging!

**Comment by ferivoq** [comment]
I joined the server my name is @ferivoq

**Review by hydralauncher — APPROVED** [review]
LGTM

**Comment by Stormm232** [comment]
Would like to know if @ferivoq is still considering to contribute to Hydra with more translations or not, since Hydra has been updated now numerous times, a ton of translation is missing, even at places where the translation should've been implemented already.

I translated the EN translation.json myself to Hungarian (based off of it), tho I am left unsure if I should pull req.. since there is an upcoming update about "Prices/Languages for Game Details"

I would appreciate any comment/answers, thanks.
(Kiwo.2 from the DC Server)

**Comment by ferivoq** [comment]
I no longer use this app so if you are a native hungarian speaker, feel free to countinue my work.

> Would like to know if @ferivoq is still considering to contribute to Hydra with more translations or not, since Hydra has been updated now numerous times, a ton of translation is missing, even at places where the translation should've been implemented already.

**Comment by Stormm232** [comment]
I am, that is the main reason I asked you about the translation.
Aaand i am aiming to do so, bit new to GitHub and all that but I might be able to manage it, or may not. We will see.
Thank you for your answer, appreciate it!

**Comment by ferivoq** [comment]
> I am, that is the main reason I asked you about the translation. Aaand i am aiming to do so, bit new to GitHub and all that but I might be able to manage it, or may not. We will see. Thank you for your answer, appreciate it!

Alright. Sok szerencsét :)

**Pull request merged**
