### PR TITLE
Add Ukrainian localization.

### PR DESCRIPTION
**Pull request by DenisCooper09**

### CODE REVIEW

**Comment by zamitto** [comment]
Ukranian localization has already been added in #296 
@piradata and @squidsdev, could you double check if it should be "uk"or "ua" characters for the localization?

**Comment by piradata** [comment]
its `uk` according to https://en.m.wikipedia.org/wiki/IETF_language_tag

**Comment by piradata** [comment]
i checked the lib we use and it has this link as a reference @zamitto

**Comment by zamitto** [comment]
> i checked the lib we use and it has this link as a reference @zamitto 

Thanks! I will leave the library doc page that references the link you said in the previous comment here as well:

https://www.i18next.com/principles/translation-resolution

**Pull request closed without merging**
