### PR TITLE
DE translation

### PR DESCRIPTION
**Pull request by xxDRV**

### CODE REVIEW

**Review by zamitto — CHANGES_REQUESTED** [review]
You also need to add an export of your translation file to `src/locales/index.ts`

**Comment by xxDRV** [comment]
> You also need to add an export of your translation file to `src/locales/index.ts`

Done! It's ready

**Review by hydralauncher — CHANGES_REQUESTED** [review]

**Review by xxDRV — COMMENTED** [review]
New line added, translation importet

**Comment by zamitto** [comment]
Could you update your branch with main again, please? We had to revert a PR recently

**Pull request closed without merging**
