### PR TITLE
Add UA translation Translated the missing lines in RU Add README.ru.md translated to ru Update README.md add button switch lang to ru

### PR DESCRIPTION
**Pull request by Tunchichi**
Add UA translation
Translated the missing lines in RU
Add README.ru.md translated to ru
Update README.md add button switch lang to ru

### CODE REVIEW

**Comment by Tunchichi** [comment]
The button is configured for the main repository. In my fork dont works

**Comment by Suburbanno** [comment]
Better to break these changes into multiple PRs.

**Comment by Tunchichi** [comment]
> Better to break these changes into multiple PRs.

how do I do this?

**Comment by Suburbanno** [comment]
> > Better to break these changes into multiple PRs.
> 
> how do I do this?

Close the PR and open new separate PRs, one for the UA translation and one for adding new lines in the RU translation, etc.

**Comment by Tunchichi** [comment]
tysm

> > > Better to break these changes into multiple PRs.
> > 
> > 
> > how do I do this?
> 
> Close the PR and open new separate PRs, one for the UA translation and one for adding new lines in the RU translation, etc.

tysm

**Pull request closed without merging**
